{% set name = "jaxtyping" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxtyping-{{ version }}.tar.gz
  sha256: 55e9784228fdb4749392f00990bfeb103c8e6399db5c3945f31898aa3fca56aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jax >=0.3.4
    - numpy >=1.20.0
    - typeguard >=2.13.3
    - typing-extensions >=4.2.0

test:
  imports:
    - jaxtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jaxtyping
  summary: Type annotations and runtime checking for shape and dtype of JAX arrays, and PyTrees.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
