{% set name = "jaxtyping" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxtyping-{{ version }}.tar.gz
  sha256: 5b78abbba18e0ca5b4c0870c965e204e0cdfadc1d385c24a0e1fcc15d6b3680d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.20.0
    - typeguard >=2.13.3
    - typing-extensions >=3.7.4.1

test:
  imports:
    - jaxtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jaxtyping
  summary: Type annotations and runtime checking for shape and dtype of JAX arrays, and PyTrees.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
